### PR TITLE
Portfolio Site - Elaine B.

### PR DESCRIPTION
**Pull request by ghost**
https://elaine-bergstrom.netlify.app/

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
Hodor, hodor, hodor hodor. Hodor... Hodor hodor. HODOR hodor, hodor. Hodor? Hodor? Hodor, hodor. Hodor. Hodor, hodor. Hodor. Hodor. Hodor? Hodor, hodor, hodor hodor.
 
Send me a Raven when you finish your site and fill it with your content 😸

**Review by ghost — COMMENTED** [review]
@KarolCislowski sending a 3-eyed raven your way, I've completed and updated my portfolio site. :)

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
As You can see it would be better to make your content a little bit narrower because on the ultrawide screen you need to move your neck to read the sentence from beginning to the end 😸 
image

And this blue underlining is not very nice :(
image

**Comment by ghost** [comment]
@KarolCislowski I realised some of the text colorization issues you pointed out were in the firefox browser (I had been using chrome). Next time I'll remember to double check how it appears in more browsers. :) it should look better now!

**Review by KarolCislowski — APPROVED** [review]
👍🏻

**Pull request closed without merging**
