### PR TITLE
css almost done (no testing or accessibility yet)

### PR DESCRIPTION
**Pull request by Martno96**
Unfortunately this is as far as I have managed to get this week, but I'm handing it in for now anyways to maybe get some pointers on what I got so far. The code isn't very well commented in its current state, so apologies for that.

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

**Comment by KarolCislowski** [comment]
You still didn't provide the link to the hosted portfolio

**Comment by Martno96** [comment]
> 
> 
> You still didn't provide the link to the hosted portfolio

Hi Karol! Really sorry about delaying this for so long, especially since it was an easy fix. Will try to be quicker in the future, thanks for your patience. The build link is now in the readme

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
It is really nice app but you need to change the grid for a bigger screens
image

**Review by KarolCislowski — APPROVED** [review]
It is a nice page 🎉 , but you should have 2 projects per row on desktop screen size.

**Pull request closed without merging**
