### PR TITLE
Hannah Jesinkey, Portfolio

### PR DESCRIPTION
**Pull request by jesinkey**
I definetly lost momentum this week and couldn't manage to muster the motivation to finish my portfolio now. I'll keep this as a work-in-progress and keep touching up the site as the course goes along. I would still like feedback on the little i've completed so far!

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
You didn't provide a link to the hosted version of your site. Please do it ASAP to make me possible to test it.

**Comment by jesinkey** [comment]
Hi! Sorry: https://hannahportfoliotechnigo.netlify.app/

**Comment by jesinkey** [comment]
Hi! I've now updated the portfolio. Here is the published link as well: hannah-jesinkey-portfolio.netlify.app

**Comment by KarolCislowski** [comment]
https://hannahportfoliotechnigo.netlify.app/
HTTP ERROR 404 😢

**Comment by jesinkey** [comment]
Oh no! Here is the right link: https://hannah-jesinkey-portfolio.netlify.app
So sorry, must have copied my old deployment

**Review by KarolCislowski — APPROVED** [review]
The composition is nice. But you need to work on your text contrast. I will approve it, but please work on your fonts to make them more readable.
image

**Pull request closed without merging**
